repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff-check
        name: ruff lint & sort imports
        args: ["--fix", "--select", "I"]
      - id: ruff-format
        name: ruff format
        args: []
